import { useNavigate } from 'react-router-dom'
import { seedKatieIfEmpty } from '../firebase/events'

export default function UserSelect() {
  const navigate = useNavigate()

  async function selectUser(userId) {
    if (userId === 'katie') {
      await seedKatieIfEmpty('katie')
    }
    navigate(`/feed/${userId}`)
  }

  return (
    <div className="min-h-screen bg-espn-darker flex flex-col">
      {/* ESPN-style header */}
      <header className="bg-espn-red px-6 py-4 flex items-center gap-3">
        <div className="text-white font-black text-3xl tracking-tight">ESPN</div>
        <div className="text-white/60 text-sm font-medium uppercase tracking-widest">
          Generative UI Demo
        </div>
      </header>

      <div className="flex-1 flex flex-col items-center justify-center px-6 py-16">
        <div className="mb-10 text-center">
          <h1 className="text-white font-black text-4xl mb-3 tracking-tight">
            Choose Your Profile
          </h1>
          <p className="text-espn-muted text-base max-w-md">
            Each user gets a personalized sports feed generated by AI based on
            their click and search history.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 w-full max-w-2xl">
          {/* User 1 card */}
          <button
            onClick={() => selectUser('user1')}
            className="group bg-espn-gray border border-espn-lightgray rounded-lg p-8 text-left hover:border-espn-red transition-all duration-200 hover:bg-espn-lightgray"
          >
            <div className="text-4xl mb-4">👤</div>
            <div className="text-white font-bold text-xl mb-2">Guest User</div>
            <div className="text-espn-muted text-sm leading-relaxed">
              Start fresh with zero history. Interact with the site and watch
              your feed personalize over time. Reset anytime to demonstrate the
              cold-start experience.
            </div>
            <div className="mt-5 inline-flex items-center gap-2 text-espn-red font-semibold text-sm group-hover:gap-3 transition-all">
              Start fresh
              <span>→</span>
            </div>
          </button>

          {/* Katie card */}
          <button
            onClick={() => selectUser('katie')}
            className="group bg-espn-gray border border-espn-lightgray rounded-lg p-8 text-left hover:border-espn-red transition-all duration-200 hover:bg-espn-lightgray"
          >
            <div className="text-4xl mb-4">🥍</div>
            <div className="text-white font-bold text-xl mb-2">Katie</div>
            <div className="text-espn-muted text-sm leading-relaxed">
              Pre-loaded with a real sports fan's history — college lacrosse,
              golf, and Masters betting. Shows how well the AI personalizes once
              it knows you.
            </div>
            <div className="mt-5 inline-flex items-center gap-2 text-espn-red font-semibold text-sm group-hover:gap-3 transition-all">
              Load profile
              <span>→</span>
            </div>
          </button>
        </div>

        <p className="mt-10 text-espn-muted text-xs text-center max-w-sm">
          Click history and searches are stored in Firebase Firestore. The AI
          (Gemini) generates a new React UI layout based on your accumulated
          context.
        </p>
      </div>
    </div>
  )
}
